/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para gerenciamento de treinos
 * OpenAPI spec version: 1.0.0
 */
import { api } from '../api-client'
export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay]

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
  /** @minimum 0 */
  order: number
}

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay
  isRest?: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[]
}

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[]
}

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay]

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
  /** @minimum 0 */
  order: number
}

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay
  isRest: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[]
}

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @minLength 1 */
  name: string
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[]
}

export type CreateWorkoutPlan400 = {
  error: string
  code: string
}

export type CreateWorkoutPlan401 = {
  error: string
  code: string
}

export type CreateWorkoutPlan404 = {
  error: string
  code: string
}

export type CreateWorkoutPlan500 = {
  error: string
  code: string
}

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive
}

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive]

export const ListWorkoutPlansActive = {
  true: 'true',
  false: 'false',
} as const

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay]

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @minLength 1 */
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string
}

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay
  isRest: boolean
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: string | null
  exercisesCount: number
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[]
}

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  isActive: boolean
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[]
}

export type ListWorkoutPlans400 = {
  error: string
  code: string
}

export type ListWorkoutPlans401 = {
  error: string
  code: string
}

export type ListWorkoutPlans500 = {
  error: string
  code: string
}

export type UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay]

export const UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type UpdateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id?: string
  /** @minLength 1 */
  name?: string
  /** @minimum 1 */
  sets?: number
  /** @minimum 1 */
  reps?: number
  /** @minimum 1 */
  restTimeInSeconds?: number
  /** @minimum 0 */
  order?: number
}

export type UpdateWorkoutPlanBodyWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id?: string
  /** @minLength 1 */
  name?: string
  weekDay?: UpdateWorkoutPlanBodyWorkoutDaysItemWeekDay
  isRest?: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds?: number
  coverImageUrl?: string
  exercises?: UpdateWorkoutPlanBodyWorkoutDaysItemExercisesItem[]
}

export type UpdateWorkoutPlanBody = {
  /** @minLength 1 */
  name?: string
  workoutDays?: UpdateWorkoutPlanBodyWorkoutDaysItem[]
}

export type UpdateWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof UpdateWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof UpdateWorkoutPlan200WorkoutDaysItemWeekDay]

export const UpdateWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type UpdateWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  weekDay: UpdateWorkoutPlan200WorkoutDaysItemWeekDay
  isRest: boolean
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: string | null
  exercisesCount: number
}

export type UpdateWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  workoutDays: UpdateWorkoutPlan200WorkoutDaysItem[]
}

export type UpdateWorkoutPlan400 = {
  error: string
  code: string
}

export type UpdateWorkoutPlan401 = {
  error: string
  code: string
}

export type UpdateWorkoutPlan404 = {
  error: string
  code: string
}

export type UpdateWorkoutPlan500 = {
  error: string
  code: string
}

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay]

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay
  isRest: boolean
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: string | null
  exercisesCount: number
}

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[]
}

export type GetWorkoutPlan400 = {
  error: string
  code: string
}

export type GetWorkoutPlan401 = {
  error: string
  code: string
}

export type GetWorkoutPlan403 = {
  error: string
  code: string
}

export type GetWorkoutPlan404 = {
  error: string
  code: string
}

export type GetWorkoutPlan500 = {
  error: string
  code: string
}

export type AddWorkoutDayBodyWeekDay =
  (typeof AddWorkoutDayBodyWeekDay)[keyof typeof AddWorkoutDayBodyWeekDay]

export const AddWorkoutDayBodyWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type AddWorkoutDayBodyExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
  /** @minimum 0 */
  order: number
}

export type AddWorkoutDayBody = {
  /** @minLength 1 */
  name: string
  weekDay: AddWorkoutDayBodyWeekDay
  isRest?: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises?: AddWorkoutDayBodyExercisesItem[]
}

export type AddWorkoutDay201WeekDay =
  (typeof AddWorkoutDay201WeekDay)[keyof typeof AddWorkoutDay201WeekDay]

export const AddWorkoutDay201WeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type AddWorkoutDay201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  weekDay: AddWorkoutDay201WeekDay
  isRest: boolean
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: string | null
  exercisesCount: number
}

export type AddWorkoutDay400 = {
  error: string
  code: string
}

export type AddWorkoutDay401 = {
  error: string
  code: string
}

export type AddWorkoutDay404 = {
  error: string
  code: string
}

export type AddWorkoutDay500 = {
  error: string
  code: string
}

export type RemoveWorkoutDay400 = {
  error: string
  code: string
}

export type RemoveWorkoutDay401 = {
  error: string
  code: string
}

export type RemoveWorkoutDay404 = {
  error: string
  code: string
}

export type RemoveWorkoutDay500 = {
  error: string
  code: string
}

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay]

export const GetWorkoutDay200WeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @minLength 1 */
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string
}

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string
  /** @nullable */
  startedAt?: string | null
  /** @nullable */
  completedAt?: string | null
}

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  weekDay: GetWorkoutDay200WeekDay
  isRest: boolean
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: string | null
  exercisesCount: number
  exercises: GetWorkoutDay200ExercisesItem[]
  sessions: GetWorkoutDay200SessionsItem[]
}

export type GetWorkoutDay400 = {
  error: string
  code: string
}

export type GetWorkoutDay401 = {
  error: string
  code: string
}

export type GetWorkoutDay403 = {
  error: string
  code: string
}

export type GetWorkoutDay404 = {
  error: string
  code: string
}

export type GetWorkoutDay500 = {
  error: string
  code: string
}

export type CreateWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string
}

export type CreateWorkoutSession400 = {
  error: string
  code: string
}

export type CreateWorkoutSession401 = {
  error: string
  code: string
}

export type CreateWorkoutSession404 = {
  error: string
  code: string
}

export type CreateWorkoutSession409 = {
  error: string
  code: string
}

export type CreateWorkoutSession500 = {
  error: string
  code: string
}

export type CompleteWorkoutSessionBody = {
  completedAt: unknown
}

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  startedAt: string
  completedAt: string
}

export type CompleteWorkoutSession400 = {
  error: string
  code: string
}

export type CompleteWorkoutSession401 = {
  error: string
  code: string
}

export type CompleteWorkoutSession404 = {
  error: string
  code: string
}

export type CompleteWorkoutSession500 = {
  error: string
  code: string
}

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  weekDay:
    | 'MONDAY'
    | 'TUESDAY'
    | 'WEDNESDAY'
    | 'THURSDAY'
    | 'FRIDAY'
    | 'SATURDAY'
    | 'SUNDAY'
  isRest: boolean
  estimatedDurationInSeconds: number
  /** @nullable */
  coverImageUrl?: string | null
  exercisesCount: number
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string
} | null

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean
    workoutDayStarted: boolean
  }
}

export type GetHomeData200 = {
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  activeWorkoutPlanId: string | null
  /** @nullable */
  todayWorkoutDay: GetHomeData200TodayWorkoutDay
  workoutStreak: number
  consistencyByDay: GetHomeData200ConsistencyByDay
}

export type GetHomeData400 = {
  error: string
  code: string
}

export type GetHomeData401 = {
  error: string
  code: string
}

export type GetHomeData500 = {
  error: string
  code: string
}

export type GetStatsParams = {
  from: unknown
  to: unknown
}

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean
    workoutDayStarted: boolean
  }
}

export type GetStats200 = {
  workoutStreak: number
  consistencyByDay: GetStats200ConsistencyByDay
  completedWorkoutsCount: number
  conclusionRate: number
  totalTimeInSeconds: number
}

export type GetStats400 = {
  error: string
  code: string
}

export type GetStats401 = {
  error: string
  code: string
}

export type GetStats500 = {
  error: string
  code: string
}

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string
  userName: string
  weightInGrams: number
  heightInCentimeters: number
  age: number
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  bodyFatPercentage: number | null
  /** @nullable */
  goal?: string | null
  availableDays?: string[]
  /** @nullable */
  physicalLimitations?: string | null
} | null

export type GetUserTrainData401 = {
  error: string
  code: string
}

export type PostMeTrainingDataBody = {
  /** @minimum 1 */
  weightInGrams?: number
  /** @minimum 1 */
  heightInCentimeters?: number
  /** @minimum 1 */
  age?: number
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage?: number
  goal?: string
  availableDays?: string[]
  physicalLimitations?: string
}

export type PostMeTrainingData200 = {
  userId: string
  weightInGrams: number
  heightInCentimeters: number
  age: number
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  bodyFatPercentage: number | null
  /** @nullable */
  goal?: string | null
  availableDays?: string[]
  /** @nullable */
  physicalLimitations?: string | null
}

export type PostMeTrainingData401 = {
  error: string
  code: string
}

/**
 * @summary Create a new workout plan
 */
export const createWorkoutPlan = (
  createWorkoutPlanBody: CreateWorkoutPlanBody
) => {
  return api<CreateWorkoutPlan201>({
    url: `/workout-plans`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createWorkoutPlanBody,
  })
}

/**
 * @summary List workout plans
 */
export const listWorkoutPlans = (params?: ListWorkoutPlansParams) => {
  return api<ListWorkoutPlans200Item[]>({
    url: `/workout-plans`,
    method: 'GET',
    params,
  })
}

/**
 * @summary Update an existing workout plan (partial updates)
 */
export const updateWorkoutPlan = (
  id: string,
  updateWorkoutPlanBody: UpdateWorkoutPlanBody
) => {
  return api<UpdateWorkoutPlan200>({
    url: `/workout-plans/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateWorkoutPlanBody,
  })
}

/**
 * @summary Get a workout plan by ID
 */
export const getWorkoutPlan = (id: string) => {
  return api<GetWorkoutPlan200>({ url: `/workout-plans/${id}`, method: 'GET' })
}

/**
 * @summary Add a new day to an existing workout plan
 */
export const addWorkoutDay = (
  planId: string,
  addWorkoutDayBody: AddWorkoutDayBody
) => {
  return api<AddWorkoutDay201>({
    url: `/workout-plans/${planId}/days`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addWorkoutDayBody,
  })
}

/**
 * @summary Remove a day from a workout plan
 */
export const removeWorkoutDay = (planId: string, dayId: string) => {
  return api<unknown>({
    url: `/workout-plans/${planId}/days/${dayId}`,
    method: 'DELETE',
  })
}

/**
 * @summary Get a workout day by ID
 */
export const getWorkoutDay = (planId: string, dayId: string) => {
  return api<GetWorkoutDay200>({
    url: `/workout-plans/${planId}/days/${dayId}`,
    method: 'GET',
  })
}

/**
 * @summary Create a new workout session
 */
export const createWorkoutSession = (
  workoutPlanId: string,
  workoutDayId: string
) => {
  return api<CreateWorkoutSession201>({
    url: `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`,
    method: 'POST',
  })
}

/**
 * @summary Complete a workout session
 */
export const completeWorkoutSession = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  completeWorkoutSessionBody: CompleteWorkoutSessionBody
) => {
  return api<CompleteWorkoutSession200>({
    url: `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: completeWorkoutSessionBody,
  })
}

/**
 * @summary Get house dashboard data
 */
export const getHomeData = (date: unknown) => {
  return api<GetHomeData200>({ url: `/home/${date}`, method: 'GET' })
}

/**
 * @summary Get user workout statistics
 */
export const getStats = (params: GetStatsParams) => {
  return api<GetStats200>({ url: `/stats`, method: 'GET', params })
}

/**
 * @summary Get current user training data
 */
export const getUserTrainData = () => {
  return api<GetUserTrainData200>({ url: `/me`, method: 'GET' })
}

/**
 * @summary Upsert user training data
 */
export const postMeTrainingData = (
  postMeTrainingDataBody: PostMeTrainingDataBody
) => {
  return api<PostMeTrainingData200>({
    url: `/me/training-data`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postMeTrainingDataBody,
  })
}

/**
 * @summary Chat with the virtual personal trainer
 */
export const chatWithAI = () => {
  return api<void>({ url: `/ai`, method: 'POST' })
}

export type CreateWorkoutPlanResult = NonNullable<
  Awaited<ReturnType<typeof createWorkoutPlan>>
>
export type ListWorkoutPlansResult = NonNullable<
  Awaited<ReturnType<typeof listWorkoutPlans>>
>
export type UpdateWorkoutPlanResult = NonNullable<
  Awaited<ReturnType<typeof updateWorkoutPlan>>
>
export type GetWorkoutPlanResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutPlan>>
>
export type AddWorkoutDayResult = NonNullable<
  Awaited<ReturnType<typeof addWorkoutDay>>
>
export type RemoveWorkoutDayResult = NonNullable<
  Awaited<ReturnType<typeof removeWorkoutDay>>
>
export type GetWorkoutDayResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutDay>>
>
export type CreateWorkoutSessionResult = NonNullable<
  Awaited<ReturnType<typeof createWorkoutSession>>
>
export type CompleteWorkoutSessionResult = NonNullable<
  Awaited<ReturnType<typeof completeWorkoutSession>>
>
export type GetHomeDataResult = NonNullable<
  Awaited<ReturnType<typeof getHomeData>>
>
export type GetStatsResult = NonNullable<Awaited<ReturnType<typeof getStats>>>
export type GetUserTrainDataResult = NonNullable<
  Awaited<ReturnType<typeof getUserTrainData>>
>
export type PostMeTrainingDataResult = NonNullable<
  Awaited<ReturnType<typeof postMeTrainingData>>
>
export type ChatWithAIResult = NonNullable<
  Awaited<ReturnType<typeof chatWithAI>>
>
